### ISSUE TITLE
Recommendation: Create new releases for each version of library

### ISSUE THREAD

**Issue by treyshaffer** [lasarobotics/FTCAndroidLibrary#23]
Now that the library is intended to be used by multiple teams, it may be best to make a release snapshot with each push to the master branch because it will create a more organized way of telling what version each team that is using the library is on.

**Comment by smo-key** [comment]
Thank you for the suggestion, @BlurryZombie! This was our initial plan. Once we have the majority of the library stabilized and completed, we will perform a complete code conformation (as you suggested previously) and review. Then, the `staging` branch will be merged into the `master` branch, with a new tag indicating the version and major changes.

Right now, the default branch is `staging` - once we make the next release (1.0.0), this will change to `master`. We expect the first release within the next week.

Thank you for your suggestion!
