### ISSUE TITLE
FIRST Native Gamepads in MonkeyC

### ISSUE THREAD

**Issue by ehsanmasdar** [lasarobotics/FTCAndroidLibrary#38]
FIRST Native gamepads in MonkeyC will only use PRESSED/RELEASED states not HELD/NOT_PRESSED states as they should

**Comment by smo-key** [comment]
@Oksisane Are yiu saying that MonkeyC only registers 2 states, and should be registering all 4?

**Comment by ehsanmasdar** [comment]
@smo-key It's only registering button presses as the PRESSED/RELEASED states which will cause toggles to behave erratically (these are meant to trigger once on button push after which state is switched to HELD/NOT_PRESSED). Instead, we need to default to HELD/NOT_PRESSED states and ignore the special toggle functionality when reading from FIRST gamepad objects. Also, MonkeyDo needs to respect this and convert back to the true/false boolean for native gamepad objects.
