### ISSUE TITLE
Standardize Brace indentation and spacing

### ISSUE THREAD

**Issue by treyshaffer** [lasarobotics/FTCAndroidLibrary#5]
There are parts in the code where the curly braces differ in indentation and spacing. For example, Vector3 uses three different curly brace styles throughout the class.

**Comment by smo-key** [comment]
Thank you! From now on, all commits merged into `master` will have a code review and a style revision.
We also fixed this in a22169cc567bf9087dd7ab2ae040590b833f688e.
